### PR TITLE
Fix bug where mentors cannot edit names

### PR DESCRIPTION
**Pull request by mattharris5**

### CODE REVIEW

**Comment by mattharris5** [comment]
@aayush19saxena and @mitchellharper12 I believe this solves the problem - will you take a look to confirm?

**Comment by mitchellharper12** [comment]
@mattharris5: Looking through the history, https://github.com/uwdreamproject/DreamSIS/commit/58493e5120a335f858b0b74f4e33d7043545b6ec is the only suspect commit that may have cause the regression, but I can't tell exactly how.

It appears to me that either I'm missing something, or this has been broken for a while.

**Comment by mattharris5** [comment]
I think the "new record" bug has been an issue for awhile but never surfaced because we previously didn't modify the display in the UI based on this check.

For existing records, that's a newly introduced bug from our Mentee UI feature changes. It turns out that `@person` is not set in that view so it was returning `nil` under the hood and always returning false. Using `byebug` helped me step through it and figure that out.

If these changes look OK I will push today.

**Comment by mitchellharper12** [comment]
Sounds good, and everything looks good to me

**Pull request merged**
