### PR TITLE
Add searchkick and elasticsearch

### PR DESCRIPTION
**Pull request by aayush19saxena**
Hey @mattharris5 @mitchellharper12 I'm planning to switch all the searching to `searchkick` which is a robust searching gem. Let me know your thoughts!

### CODE REVIEW

**Comment by aayush19saxena** [comment]
In my last commit, although I'm getting the correct url path, my variable `@mentors` seems to be empty but not `nil`.

**Comment by mattharris5** [comment]
This is great, let's work together on this. One thing that we'll need to keep in mind is the multi-tenancy, so [this post](https://www.tiagoamaro.com.br/2014/12/11/multi-tenancy-with-searchkick/) might be helpful.

One thing is that I think this should be part of DreamSIS 4, not the current version. It will be much easier to accomplish a lot of these things with the switch to Rails 4, Bootstrap, jQuery 2, and Postgres.

I'm not sure how to go about the devops flow here (@mitchellharper12, any suggestions?). We should probably do one of the following:

1. Close this PR and change it to target `migration/heroku` instead of `master`
2. Wait until we've merged DreamSIS 4 into `master` and then make the necessary updates in this branch.

I would lean to option 1.

**Comment by aayush19saxena** [comment]
Yes, I was looking into multi-tenancy in the post at Pivotal Tracker. So before that, I just wanted to play around with it and test to see how it could work :)

I agree, once we have newer versions of the technologies, it'll be better for us to implement this. So, just a question in mind, wouldn't it be better if we wait until we have DreamSIS 4 ready?

**Comment by mitchellharper12** [comment]
@mattharris5 Option 1 definitely makes sense, if this branch is going to have a dependency on DreamSIS 4 features. Otherwise, we would either have DreamSIS 4 commits on a commit graph branch outside `migration/heroku` (which seems messy) or have to completely pause development on this branch.

Moving this to have `migration/heroku` as the canonical upstream branch gives this a cleaner path for getting merged into master.

**Comment by mattharris5** [comment]
Alright, that makes sense to me too. @aayush19saxena let's close this PR and create a new branch that is based off `migration/heroku`. As we work on the DreamSIS 4 changes you can keep the upstream branch up to date, and that way we can both work on the searching features before merging them in. Make sense to you?

**Comment by aayush19saxena** [comment]
Makes sense to me, Matt!

**Pull request closed without merging**
